name: Self-hosted Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  do-the-job:
    name: Test on self-hosted runner
    runs-on: self-hosted
    steps:
    - name: NVIDIA-SMI
      run: nvidia-smi
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Cache
      uses: actions/cache@v2.1.3
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          ~/.cache
        # An explicit key for restoring and saving the cache
        key: evaldata-cache-4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install -e .[dev]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -vv --cov=lm_eval/ tests/

